version: '3'

services:
  aptima-building-ubuntu-2204:
    build: .
    image: aptima/building/ubuntu/22.04
    tty: true
    volumes:
      - /tmp/aptima:/tmp/aptima
    environment:
      - PATH=/tmp/aptima/aptima_gn:$PATH
