name: Build - mac

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "tools/**"
      - "docs/**"
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/build_mac.yml"
      - "**.md"

jobs:
  build-mac-arm64:
    concurrency:
      group: build-mac-arm64-${{ github.head_ref }}-${{ matrix.build_type }}
      cancel-in-progress: true
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [debug, release]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: false

      - name: Set ulimit and sysctl
        run: |
          # Because there are concurrent test cases which involves many
          # concurrent socket connections, we need to enlarge the maximum number
          # of the opened file descriptor.
          ulimit -n 102400

          # Because there are concurrent test cases which will create many
          # concurrent connections simutaneously, we increase the TCP listening
          # backlog value to 8192.
          sudo sysctl -w kern.ipc.somaxconn=8192
        shell: bash

      - name: Install tools and dependencies
        run: |

          if [ ${{ matrix.build_type }} == "debug" ]; then
            # Since the TEN runtime and TEN manager are a combination of C and
            # Rust, to enable ASan, the ASan versions used by both the C and
            # Rust compilation environments must be consistent. Therefore, it is
            # necessary to lock the LLVM and Rust versions to enable ASan.
            brew install llvm@18
            rustup default nightly-2024-07-19
          else
            rustup default nightly
          fi

          brew install tree
          pip3 install --use-pep517 python-dotenv jinja2
          go install golang.org/dl/go1.20.12@latest && go1.20.12 download
          go env -w GOFLAGS="-buildvcs=false"
          cargo install --force cbindgen

      - name: Build
        run: |
          if [ ${{ matrix.build_type }} == "debug" ]; then
            export PATH="/opt/homebrew/opt/llvm@18/bin:$PATH"
          fi
          export PATH=$(pwd)/core/axis_gn:$PATH
          echo $PATH

          df -h .

          tgn gen mac arm64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true axis_enable_serialized_rust_action=true axis_rust_enable_gen_cargo_config=false axis_enable_cargo_clean=true axis_enable_python_binding=false axis_enable_rust_incremental_build=false axis_manager_enable_frontend=false axis_enable_integration_tests_prebuilt=false axis_enable_nodejs_binding=false

          tgn build mac arm64 ${{ matrix.build_type }}

          df -h .
          tree -I 'gen|obj' out

      - name: Run Tests (axis_utils_unit_test)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/mac/arm64/tests/standalone/axis_utils_unit_test
          out/mac/arm64/tests/standalone/axis_utils_unit_test

      - name: Run Tests (axis_runtime_unit_test)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/mac/arm64/tests/standalone/axis_runtime_unit_test
          out/mac/arm64/tests/standalone/axis_runtime_unit_test

      - name: Run Tests (axis_runtime_smoke_test)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/mac/arm64/tests/standalone/axis_runtime_smoke_test
          out/mac/arm64/tests/standalone/axis_runtime_smoke_test
      #   continue-on-error: true
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Run Tests (axis_rust standalone tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/mac/arm64/tests/standalone/axis_rust

          chmod +x unit_test
          chmod +x integration_test

          ./unit_test || { echo "axis_rust unit test failed"; exit 1; }
          ./integration_test || { echo "axis_rust integration test failed"; exit 1; }

      - name: Run Tests (axis_manager standalone tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/mac/arm64/tests/standalone/axis_manager

          chmod +x unit_test

          ./unit_test || { echo "axis_manager unit test failed"; exit 1; }

      - name: Install Python dependencies via script
        run: |
          python .github/tools/setup_pytest_dependencies.py

      - name: Run Tests (axis_manager pytest tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/mac/arm64/
          pytest -s tests/axis_manager/

      - name: Run tests (axis_runtime integration tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          if [ ${{ matrix.build_type }} == "debug" ]; then
            export PATH="/opt/homebrew/opt/llvm@18/bin:$PATH"
          fi
          export PATH=$(pwd)/core/axis_gn:$PATH
          cd out/mac/arm64/
          pytest -s tests/axis_runtime/integration/
      #   continue-on-error: true

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

  build-mac-x64:
    concurrency:
      group: build-mac-x64-${{ github.head_ref }}-${{ matrix.build_type }}
      cancel-in-progress: true
    runs-on: macos-13
    strategy:
      matrix:
        build_type: [release]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: false

      - name: Set ulimit and sysctl
        run: |
          # Because there are concurrent test cases which involves many
          # concurrent socket connections, we need to enlarge the maximum number
          # of the opened file descriptor.
          ulimit -n 102400

          # Because there are concurrent test cases which will create many
          # concurrent connections simutaneously, we increase the TCP listening
          # backlog value to 8192.
          sudo sysctl -w kern.ipc.somaxconn=8192
        shell: bash

      - name: Install tools and dependencies
        run: |

          if [ ${{ matrix.build_type }} == "debug" ]; then
            # Since the TEN runtime and TEN manager are a combination of C and
            # Rust, to enable ASan, the ASan versions used by both the C and
            # Rust compilation environments must be consistent. Therefore, it is
            # necessary to lock the LLVM and Rust versions to enable ASan.
            brew install llvm@18
            rustup default nightly-2024-07-19
          else
            rustup default nightly
          fi

          brew install tree
          pip3 install --use-pep517 python-dotenv jinja2
          go install golang.org/dl/go1.20.12@latest && go1.20.12 download
          go env -w GOFLAGS="-buildvcs=false"
          cargo install --force cbindgen

      - name: Build
        run: |
          if [ ${{ matrix.build_type }} == "debug" ]; then
            export PATH="/usr/local/opt/llvm@18/bin:$PATH"
          fi
          export PATH=$(pwd)/core/axis_gn:$PATH
          echo $PATH

          df -h .

          tgn gen mac x64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true axis_enable_serialized_rust_action=true axis_rust_enable_gen_cargo_config=false axis_enable_cargo_clean=true axis_enable_python_binding=false axis_enable_rust_incremental_build=false axis_manager_enable_frontend=false axis_enable_integration_tests_prebuilt=false axis_enable_nodejs_binding=false

          tgn build mac x64 ${{ matrix.build_type }}

          df -h .
          tree -I 'gen|obj' out
      #   continue-on-error: true
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Run Tests (axis_utils_unit_test)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/mac/x64/tests/standalone/axis_utils_unit_test
          out/mac/x64/tests/standalone/axis_utils_unit_test

      - name: Run Tests (axis_runtime_unit_test)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/mac/x64/tests/standalone/axis_runtime_unit_test
          out/mac/x64/tests/standalone/axis_runtime_unit_test

      - name: Run Tests (axis_runtime_smoke_test)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/mac/x64/tests/standalone/axis_runtime_smoke_test
          out/mac/x64/tests/standalone/axis_runtime_smoke_test

      - name: Run Tests (axis_rust standalone tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/mac/x64/tests/standalone/axis_rust

          chmod +x unit_test
          chmod +x integration_test

          ./unit_test || { echo "axis_rust unit test failed"; exit 1; }
          ./integration_test || { echo "axis_rust integration test failed"; exit 1; }

      - name: Run Tests (axis_manager standalone tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/mac/x64/tests/standalone/axis_manager

          chmod +x unit_test

          ./unit_test || { echo "axis_manager unit test failed"; exit 1; }

      - name: Install Python dependencies via script
        run: |
          python .github/tools/setup_pytest_dependencies.py

      - name: Run Tests (axis_manager pytest tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/mac/x64/
          pytest -s tests/axis_manager/

      - name: Run tests (axis_runtime integration tests)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          if [ ${{ matrix.build_type }} == "debug" ]; then
            export PATH="/usr/local/opt/llvm@18/bin:$PATH"
          fi
          export PATH=$(pwd)/core/axis_gn:$PATH
          cd out/mac/x64/
          pytest -s tests/axis_runtime/integration/
      #   continue-on-error: true

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

  # Building axis_runtime without the axis_rust library (i.e., axis_enable_axis_rust_apis=false).
  build-mac-arm64-without-axis-rust:
    concurrency:
      group: build-mac-arm64-without-axis-rust-${{ github.head_ref }}-${{ matrix.build_type }}
      cancel-in-progress: true
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [debug]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: false

      - name: Set ulimit and sysctl
        run: |
          # Because there are concurrent test cases which involves many
          # concurrent socket connections, we need to enlarge the maximum number
          # of the opened file descriptor.
          ulimit -n 102400

          # Because there are concurrent test cases which will create many
          # concurrent connections simutaneously, we increase the TCP listening
          # backlog value to 8192.
          sudo sysctl -w kern.ipc.somaxconn=8192
        shell: bash

      - name: Install tools and dependencies
        run: |

          if [ ${{ matrix.build_type }} == "debug" ]; then
            # Since the TEN runtime and TEN manager are a combination of C and
            # Rust, to enable ASan, the ASan versions used by both the C and
            # Rust compilation environments must be consistent. Therefore, it is
            # necessary to lock the LLVM and Rust versions to enable ASan.
            brew install llvm@18
            rustup default nightly-2024-07-19
          else
            rustup default nightly
          fi

          brew install tree
          pip3 install --use-pep517 python-dotenv jinja2
          go install golang.org/dl/go1.20.12@latest && go1.20.12 download
          go env -w GOFLAGS="-buildvcs=false"
          cargo install --force cbindgen

      - name: Build
        run: |
          if [ ${{ matrix.build_type }} == "debug" ]; then
            export PATH="/opt/homebrew/opt/llvm@18/bin:$PATH"
          fi
          export PATH=$(pwd)/core/axis_gn:$PATH
          echo $PATH

          df -h .

          tgn gen mac arm64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true axis_enable_serialized_rust_action=true axis_rust_enable_gen_cargo_config=false axis_enable_axis_rust_apis=false axis_enable_rust_incremental_build=false axis_manager_enable_frontend=false axis_enable_integration_tests_prebuilt=false axis_enable_nodejs_binding=false

          tgn build mac arm64 ${{ matrix.build_type }}

          df -h .
          tree -I 'gen|obj' out

      - name: Run Tests (axis_runtime_smoke_test)
        env:
          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          axis_ENABLE_MEMORY_TRACKING: "true"
          axis_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/mac/arm64/tests/standalone/axis_runtime_smoke_test
          out/mac/arm64/tests/standalone/axis_runtime_smoke_test
      #   continue-on-error: true

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
